---
extends: default

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy: disable
  brackets: disable

# Exclude directories that shouldn't be linted
exclude:
  - .venv/
  - node_modules/
  - dist/
  - build/
  - .git/
  - .mypy_cache/
  - .pytest_cache/
  - htmlcov/
  - .ruff_cache/
